language: php
php:
  - 5.6
  - 7.0
  - hhvm
install:
  - phpenv config-rm xdebug.ini; true
  - composer update
  - composer require satooshi/php-coveralls
before_script:
  - mkdir -p build/logs
  - echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; true
script:
  - phpunit --coverage-clover build/logs/clover.xml
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
